import os
import pandas as pd
import requests
import base64
import hashlib

# Generate a random code_verifier (43-128 characters long)
def generate_code_verifier(length: int = 64) -> str:
    """
    Generate a random code_verifier of a given length (default is 64).

    The code_verifier is a URL-safe base64-encoded string.

    Parameters
    ----------
    length : int
        The length of the code_verifier. Must be between 43 and 128 characters.

    Returns
    -------
    str
        The code_verifier as a URL-safe base64-encoded string.
    """
    # Generate a random byte string of the given length
    # os.urandom() is a cryptographically secure method of generating random bytes
    random_bytes = os.urandom(length)

    # Encode the random bytes as a URL-safe base64 string
    # The decode() method is used to convert the bytes to a string
    # The rstrip() method is used to remove the trailing "=" padding
    verifier = base64.urlsafe_b64encode(random_bytes).decode('utf-8').rstrip("=")

    return verifier

# Generate code_challenge from the code_verifier (SHA-256 hash)
def generate_code_challenge(code_verifier: str) -> str:
    """
    Generate the code_challenge from a given code_verifier.

    The code_challenge is the SHA-256 hash of the code_verifier, encoded as a URL-safe base64 string.

    Parameters
    ----------
    code_verifier : str
        The code_verifier to generate the code_challenge from.

    Returns
    -------
    str
        The code_challenge as a URL-safe base64-encoded string.

    Notes
    -----
    The code_challenge is used in the authorization flow to verify the authenticity of the client.

    The code_challenge is generated by hashing the code_verifier with the SHA-256 algorithm, and then encoding the result as a URL-safe base64 string.

    The code_challenge is sent to the authorization server along with the code_verifier, and the server uses it to verify the client's identity.
    """
    # Calculate the SHA-256 hash of the code_verifier
    challenge = hashlib.sha256(code_verifier.encode('utf-8')).digest()

    # Encode the hash as a URL-safe base64 string
    # The decode() method is used to convert the bytes to a string
    # The rstrip() method is used to remove the trailing "=" padding
    code_challenge = base64.urlsafe_b64encode(challenge).decode('utf-8').rstrip("=")

    return code_challenge

# Step 1: Get Bearer Token
def get_bearer_token(
    username: str,  # The username to log in with.
    password: str  # The password to log in with.
) -> str | None:
    """
    Get the bearer token from the MBS API.

    Parameters
    ----------
    username : str
        The username to log in with.
    password : str
        The password to log in with.

    Returns
    -------
    str | None
        The bearer token if the login is successful, None otherwise.
    """
    # Generate code verifier and challenge for PKCE
    code_verifier = generate_code_verifier()
    code_challenge = generate_code_challenge(code_verifier)

    # Device ID for login
    device_id = "183.46.35.23"

    # Login API endpoint URL
    login_url = "https://accts.mbs.com.vn/webuaa/login"

    # Headers required for the login request
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    }

    # Payload containing login credentials and PKCE parameters
    payload = {
        "username": username,
        "password": password,
        "device_id": device_id,
        "code_challenge": code_challenge,
        "verifier": code_verifier
    }

    # Send the login request
    response = requests.post(login_url, headers=headers, data=payload)

    # Check if login is successful and extract the token
    if response.status_code == 200:
        token = response.json().get("access_token")
        if token:
            print("✅ Bearer token obtained successfully!")
            return token
        else:
            print("❌ Token not found in the response.")
    else:
        print(f"❌ Failed to log in. Status code: {response.status_code}, Response: {response.text}")
    return None

def fetch_order_deal(
    token: str,  # The bearer token obtained from the MBS API
    from_date: str,  # The start date for filtering orders or deals
    to_date: str,  # The end date for filtering orders or deals
    account: str,  # The account number to filter the orders or deals
    order_or_deal: str = "order"  # The type of data to fetch
) -> dict:
    """
    Fetch order or deal data from the MBS API.

    Parameters
    ----------
    token : str
        The bearer token obtained from the MBS API.
    from_date : str
        The start date for filtering orders or deals.
    to_date : str
        The end date for filtering orders or deals.
    account : str
        The account number to filter the orders or deals.
    order_or_deal : str, optional
        The type of data to fetch. Defaults to 'order'.

    Returns
    -------
    dict
        The JSON response from the MBS API.

    Raises
    ------
    ValueError
        If the response status code is not 200.

    Notes
    -----
    The MBS API endpoint for orders and deals is the same, the only difference is in the
    "orderOrDeal" parameter in the query string. If the parameter is "order", the API will return
    the order data, otherwise it will return the deal data.
    """
    headers = {
        'Content-Type': 'application/json',
        "authorization": f"Bearer {token}",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    }

    # Query parameters for order API
    params = {
        "fromDate": from_date,
        "toDate": to_date,
        "page": 1,
        "pageSize": 1000,
    }

    # Order API endpoint
    order_url = f"https://fot-api-web.mbs.com.vn/v1/accounts/orders/{account}"

    # Deal API endpoint
    deal_url = f"https://fot-api-web.mbs.com.vn/v1/accounts/orders/deals/{account}"

    # Send request to get order data
    if order_or_deal == "order":
        response = requests.get(order_url, headers=headers, params=params)
    elif order_or_deal == "deal":
        response = requests.get(deal_url, headers=headers, params=params)

    # Check response
    if response.status_code == 200:
        print(f"✅ {order_or_deal} data retrieved successfully!")
        return response.json()  # Display the JSON response
    else:
        print(f"❌ Failed to fetch orders. Status code: {response.status_code}, Response: {response.text}")

def get_order_merged(
    token: str,
    from_date: str,
    to_date: str,
    account: str
) -> pd.DataFrame:
    """
    Get merged order data from MBS API.

    Parameters
    ----------
    token : str
        The bearer token obtained from the MBS API.
    from_date : str
        The start date for filtering orders or deals.
    to_date : str
        The end date for filtering orders or deals.
    account : str
        The account number to filter the orders or deals.

    Returns
    -------
    pd.DataFrame
        The merged order data.

    Notes
    -----
    This function fetches order and deal data from the MBS API using the
    `fetch_order_deal` function, and then merges them together on the 'orderNo'
    column. The resulting DataFrame is then returned.

    The function first fetches the order data using the 'order' parameter, and
    then fetches the deal data using the 'deal' parameter. The two DataFrames are
    then merged together on the 'orderNo' column.

    The resulting DataFrame is then cleaned up by dropping the 'rowNo' column,
    converting the 'orderNo' column to string type, and renaming the columns to
    match the desired output format.

    Finally, the function returns the merged DataFrame.
    """
    # Fetch order data
    order = pd.DataFrame(fetch_order_deal(token, from_date=from_date, to_date=to_date, account=account, order_or_deal="order")['items'])
    # Fetch deal data
    deal = pd.DataFrame(fetch_order_deal(token, from_date=from_date, to_date=to_date, account=account, order_or_deal="deal")['items'])

    # Drop 'rowNo' column
    order = order.drop(columns=['rowNo'])
    deal = deal.drop(columns=['rowNo'])

    # Convert 'orderNo' column to string type
    order['orderNo'] = order['orderNo'].astype(str)
    deal['orderNo'] = deal['orderNo'].astype(str)

    # Merge order and deal data
    order_merged = pd.merge(order, deal, how='left', on='orderNo')

    # Clean up merged data
    order_merged['orderDate'] = pd.to_datetime(order_merged['orderDate'], dayfirst=True).dt.date
    order_merged['dueDate'] = pd.to_datetime(order_merged['dueDate'], dayfirst=True).dt.date

    columns_order = [
        'side',
        'account',
        'symbol',
        'price',
        'quantity',
        'orderStatus',
        'createdDate',
        'orderNo',
        'exchangeID',
        'matchedValue',
        'channel',
        'fillQuantity',
        'avgPrice',
        'orderPrice',
        'fillValue',
        'accountCode',
        'shareCode',
        'orderTime',
        'orderDate',
        'dueDate',
        'matchedPrice',
        'matchedVolume'
    ]
    order_merged = order_merged[columns_order]
    order_merged.columns = [
        'side',
        'account',
        'symbol',
        'price',
        'quantity',
        'order_status',
        'created_date',
        'order_no',
        'exchange',
        'matched_value',
        'channel',
        'fill_quantity',
        'avg_price',
        'order_price',
        'fill_value',
        'account_code',
        'share_code',
        'order_time',
        'order_date',
        'due_date',
        'matched_price',
        'matched_volume'
    ]

    return order_merged

def fetch_statement(
    token: str,  # The bearer token obtained from the MBS API
    from_date: str,  # The start date for filtering statements
    to_date: str,  # The end date for filtering statements
    account: str,  # The account number to filter the statements
    statement_type: str = "stock"  # The type of statement to retrieve
) -> dict:
    """
    Fetch the stock or cash statement data from the MBS API.

    Parameters
    ----------
    token : str
        The bearer token obtained from the MBS API.
    from_date : str
        The start date for filtering statements.
    to_date : str
        The end date for filtering statements.
    account : str
        The account number to filter the statements.
    statement_type : str, optional
        The type of statement to retrieve. Defaults to 'stock'.

    Returns
    -------
    dict
        The JSON response from the MBS API.

    Raises
    ------
    ValueError
        If the response status code is not 200.
    """
    # Headers for the API request
    headers = {
        'Content-Type': 'application/json',
        "authorization": f"Bearer {token}",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    }

    # Query parameters for the API request
    params = {
        "masterAccount": account,
        "account": account,
        "fromDate": from_date,
        "toDate": to_date,
        "page": 1,
        "pageSize": 1000,
    }

    # Endpoints for stock and cash statements
    stock_statement_url = "https://fot-api-web.mbs.com.vn/v1/accounts/share/statement"
    cash_statement_url = "https://fot-api-web.mbs.com.vn/v1/accounts/cash/statement"

    # Determine the correct endpoint based on the statement type
    if statement_type == "stock":
        response = requests.get(stock_statement_url, headers=headers, params=params)
    elif statement_type == "cash":
        response = requests.get(cash_statement_url, headers=headers, params=params)

    # Check the response status
    if response.status_code == 200:
        print(f"✅ {statement_type} data retrieved successfully!")
        return response.json()  # Return the JSON response
    else:
        print(f"❌ Failed to fetch {statement_type} data. Status code: {response.status_code}, Response: {response.text}")

def get_cash_statement(
    token: str,  # The bearer token obtained from the MBS API
    from_date: str,  # The start date for filtering orders
    to_date: str,  # The end date for filtering orders
    account: str  # The account number to filter the orders
) -> pd.DataFrame:
    """
    Get the cash statement data from the MBS API.

    Parameters
    ----------
    token : str
        The bearer token obtained from the MBS API.
    from_date : str
        The start date for filtering orders.
    to_date : str
        The end date for filtering orders.
    account : str
        The account number to filter the orders.

    Returns
    -------
    pd.DataFrame
        The cash statement data with columns as account, date, description, txtype, amount, entry_type
    """
    # Fetch the cash statement data from the MBS API
    fact_cash_statement = pd.DataFrame(
        fetch_statement(token, from_date=from_date, to_date=to_date, account=account, statement_type="cash")['items']
    )

    # Drop the rowNum column
    fact_cash_statement = fact_cash_statement.drop(columns=['rowNum'])

    # Convert the tradeDate column to date
    fact_cash_statement['tradeDate'] = pd.to_datetime(
        fact_cash_statement['tradeDate'], format='%Y%m%d'
    ).dt.date

    # Create a new column Txtype
    fact_cash_statement['Txtype'] = fact_cash_statement.apply(
        lambda row: 'Debit' if row['cashUp'] == 0 else 'Credit', axis=1
    )

    # Create a new column Amount
    fact_cash_statement['Amount'] = fact_cash_statement[['cashUp', 'cashDown']].max(axis=1)

    # Select the columns
    fact_cash_statement = fact_cash_statement[
        ['accountNo', 'tradeDate', 'content', 'Txtype', 'Amount', 'entryType']
    ]

    # Rename the columns
    fact_cash_statement.columns = [
        'account', 'date', 'description', 'txtype', 'amount', 'entry_type'
    ]

    return fact_cash_statement


def get_stock_statement(token, from_date, to_date, account):
    """
    Get the stock statement data from the MBS API.

    Args:
        token (str): The bearer token obtained from the MBS API.
        from_date (str): The start date for filtering orders.
        to_date (str): The end date for filtering orders.
        account (str): The account number to filter the orders.

    Returns:
        pd.DataFrame: The stock statement data with columns as account, date, trans_no, symbol, status, credit, debit, description
    """
    # Fetch the stock statement data from the MBS API
    fact_stock_statement = pd.DataFrame(
        fetch_statement(token, from_date=from_date, to_date=to_date, account=account, statement_type="stock")['items'][0]['details']
    )

    # Drop the rowNum column
    fact_stock_statement = fact_stock_statement.drop(columns=['rowNum'])

    # Convert the dueDate column to date
    fact_stock_statement['dueDate'] = pd.to_datetime(
        fact_stock_statement['dueDate'], dayfirst=True
    ).dt.date

    # Select the columns
    fact_stock_statement = fact_stock_statement[
        ['accountCode', 'dueDate', 'transNo', 'shareCode', 'shareStatus', 'shareIn', 'shareOut', 'content']
    ]

    # Rename the columns
    fact_stock_statement.columns = [
        'account', 'date', 'trans_no', 'symbol', 'status', 'credit', 'debit', 'description'
    ]

    return fact_stock_statement
