# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /Volumes/990pro/docker-share:/tmp  # Mount host directory to container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "0.0.0.0:5432:5432"  # Expose to all network interfaces

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: